<?php

namespace App\Http\Controllers;

use App\Models\Reservation;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewReservationMail;

class ReservationController extends Controller
{
    public function index()
    {
        return response()->json(['data' => Reservation::with('slots')->get()]);
    }

    public function store(Request $request)
    {
        Log::info($request->all());

        // Filter out empty/invalid slots generated by the frontend
        if ($request->has('slots') && is_array($request->slots)) {
            $filteredSlots = array_values(array_filter($request->slots, function ($slot) {
                return !empty($slot['studio_id']);
            }));
            $request->merge(['slots' => $filteredSlots]);
        }

        try {
            $validated = $request->validate([
                'slots' => 'required|array|min:1',
                'slots.*.studio_id' => 'required|integer|exists:studios,id',
                'slots.*.date' => 'required|date',
                'slots.*.start_time' => 'required|date_format:H:i',
                'slots.*.end_time' => 'required|date_format:H:i|after:slots.*.start_time',
                'name' => 'required|string',
                'email' => 'required|email',
                'phone' => 'nullable|string',
                'total_price' => 'required|numeric',
                'service_type' => 'nullable|string',
                'equipment' => 'nullable|array',
                'team' => 'nullable|array'
            ]);

            if (!auth()->check()) {
                return response()->json(['message' => 'Unauthorized'], 401);
            }

            DB::beginTransaction();

            $bookingReference = 'TS-' . time() . '-' . strtoupper(Str::random(4));
            $createdReservations = [];

            foreach ($validated['slots'] as $slot) {
                // Conflict Detection
                $exists = \App\Models\ReservationSlot::whereHas('reservation', function($q) {
                        $q->where('status', '!=', 'cancelled');
                    })
                    ->where('studio_id', $slot['studio_id'])
                    ->where('date', $slot['date'])
                    ->where(function ($query) use ($slot) {
                        $query->where('start_time', '<', $slot['end_time'])
                              ->where('end_time', '>', $slot['start_time']);
                    })
                    ->exists();

                if ($exists) {
                    DB::rollBack();
                    return response()->json([
                        'message' => "Studio is already booked for the requested time slot."
                    ], 422);
                }

                $reservation = Reservation::create([
                    'user_id' => auth()->id(),
                    'booking_reference' => $bookingReference,
                    'studio_id' => $slot['studio_id'],
                    'date' => $slot['date'],
                    'time_slot' => $slot['start_time'] . ' - ' . $slot['end_time'],
                    'service_type' => $validated['service_type'] ?? 'studio',
                    'selected_equipment' => $validated['equipment'] ?? [],
                    'selected_team_members' => $validated['team'] ?? [],
                    'customer_name' => $validated['name'],
                    'customer_email' => $validated['email'],
                    'customer_phone' => $validated['phone'] ?? null,
                    'total_price' => $validated['total_price'],
                    'status' => 'pending',
                ]);

                // Create slot for compatibility
                $reservation->slots()->create([
                    'studio_id' => $slot['studio_id'],
                    'date' => $slot['date'],
                    'start_time' => $slot['start_time'],
                    'end_time' => $slot['end_time'],
                ]);

                $createdReservations[] = $reservation->load('slots.studio', 'user', 'studio');
            }

            DB::commit();

            try {
                Mail::to('techstudio@gmail.com')->send(new NewReservationMail($createdReservations));
            } catch (\Exception $e) {
                Log::error("Mail failed: " . $e->getMessage());
            }

            return response()->json([
                'message' => 'Reservation created successfully',
                'data' => [
                    'id' => $bookingReference,
                    'booking_reference' => $bookingReference,
                    'reservations' => $createdReservations
                ]
            ], 201);

        } catch (\Illuminate\Validation\ValidationException $e) {
            Log::error($e->getMessage());
            return response()->json([
                'message' => 'Validation error',
                'errors' => $e->errors()
            ], 422);
        } catch (\Exception $e) {
            Log::error($e->getMessage());
            DB::rollBack();
            return response()->json([
                'message' => $e->getMessage(),
                'error' => $e->getMessage()
            ], 500);
        }
    }

    public function myReservations(Request $request)
    {
        $reservations = $request->user()->reservations()->with(['studio', 'slots'])->get()->map(function ($reservation) {
            
            $slotsData = $reservation->slots->map(function($slot) {
                return [
                    'date' => $slot->date,
                    'start_time' => \Carbon\Carbon::parse($slot->start_time)->format('H:i'),
                    'end_time' => \Carbon\Carbon::parse($slot->end_time)->format('H:i')
                ];
            });

            return [
                "studio" => $reservation->studio->name ?? 'Unknown Studio',
                "date" => $reservation->date,
                "time_slot" => $reservation->time_slot,
                "status" => $reservation->status,
                "booking_reference" => $reservation->booking_reference,
                "slots" => $slotsData,
                "total_price" => $reservation->total_price,
            ];
        });

        return response()->json(['data' => $reservations]);
    }

    public function cancel(Request $request, $id)
    {
        $reservations = $request->user()->reservations()->where('booking_reference', $id)->get();

        if ($reservations->isEmpty()) {
            return response()->json(['message' => 'Reservation not found or not authorized.'], 404);
        }

        foreach ($reservations as $reservation) {
            if ($reservation->status !== 'pending') {
                return response()->json(['message' => 'Only pending reservations can be cancelled.'], 400);
            }
        }

        foreach ($reservations as $reservation) {
            $reservation->status = 'cancelled';
            $reservation->save();
        }

        return response()->json(['message' => 'Reservation cancelled successfully.', 'data' => $reservations->first()]);
    }
}